default: &default
  adapter: postgresql
  encoding: unicode
  user: dannybenshi
  password: DannyPro123
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Hello_Rails_Backend_dev
test:
  <<: *default
  database: Hello_Rails_Backend_test

production:
  <<: *default
  database: Hello_Rails_Backend_production
  username: Hello_Rails_Backend
  password: <%= ENV["HELLO_RAILS_BACKEND_DATABASE_PASSWORD"] %>
